# Generated by Django 4.2.30 on 2026-08-11 23:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocoa_season', models.CharField(max_length=50)),
                ('zone_name', models.CharField(max_length=100)),
                ('society_district_name', models.CharField(max_length=100)),
                ('zone_station', models.CharField(max_length=100)),
                ('waybill_no', models.CharField(max_length=100)),
                ('dprs_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('farmer_name', models.CharField(max_length=200)),
                ('farmer_status', models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], max_length=50)),
                ('cocoa_card_id', models.CharField(max_length=100)),
                ('kk_id', models.CharField(blank=True, max_length=100, null=True)),
                ('kilos', models.FloatField()),
                ('amount_ghc', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='purchases.purchasesession')),
            ],
        ),
    ]
