# Generated by Django 4.2.30 on 2026-08-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesession',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasesession',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
