# Generated by Django 4.2.30 on 2026-08-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchasesession_latitude_purchasesession_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.CharField(blank=True, max_length=150, null=True)),
                ('zone', models.CharField(blank=True, max_length=150, null=True)),
                ('station_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('kk_id_num', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('phone_numbers', models.CharField(blank=True, max_length=200, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('field_size', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('bags', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
