# Generated by Django 4.2.30 on 2026-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_fieldagentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesession',
            name='zone_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
