# Generated by Django 4.2.30 on 2026-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_delivery_district_region_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesession',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
